name: token_generator
description: A Flutter app for generating patient queue tokens in a clinic.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  esc_pos_utils: ^1.1.0
  flutter_blue_plus: ^1.31.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
